version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - SECRET_KEY=samplesecret123
      - ALLOWED_HOSTS=18.231.118.122,ec2-18-231-118-122.sa-east-1.compute.amazonaws.com

  proxy:
    build:
      context: ./proxy
    ports:
      - "8080:8080"
    depends_on:
      - app

  elasticsearch:
    image: launcher.gcr.io/google/elasticsearch2
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
        - proxy

volumes:
  static_data: