version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - SECRET_KEY=samplesecret123
      - ALLOWED_HOSTS=3.137.183.138,ec2-3-137-183-138.us-east-2.compute.amazonaws.com

  proxy:
    build:
      context: ./proxy
    ports:
      - "8080:8080"
    depends_on:
      - app

  elasticsearch:
    image: launcher.gcr.io/google/elasticsearch2
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
        - proxy

volumes:
  static_data: