# Generated by Django 3.1.1 on 2020-09-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_ordem', models.TextField(blank=True, db_column='NUMERO DE ORDEM', null=True)),
                ('anomes', models.IntegerField(blank=True, db_column='ANOMES', null=True)),
                ('cod_ncm', models.IntegerField(blank=True, db_column='COD.NCM', null=True)),
                ('descricao_do_codigo_ncm', models.TextField(blank=True, db_column='DESCRICAO DO CODIGO NCM', null=True)),
                ('pais', models.TextField(blank=True, db_column='PAIS', null=True)),
                ('pais_de_origem', models.TextField(blank=True, db_column='PAIS DE ORIGEM', null=True)),
                ('pais_0_field', models.TextField(blank=True, db_column='PAIS_[0]', null=True)),
                ('pais_de_aquisicao', models.TextField(blank=True, db_column='PAIS DE AQUISICAO', null=True)),
                ('und_estat_field', models.IntegerField(blank=True, db_column='UND.ESTAT.', null=True)),
                ('unidade_de_medida', models.TextField(blank=True, db_column='UNIDADE DE MEDIDA', null=True)),
                ('unidade_comerc_field', models.TextField(blank=True, db_column='UNIDADE COMERC.', null=True)),
                ('descricao_do_produto', models.TextField(blank=True, db_column='DESCRICAO DO PRODUTO', null=True)),
                ('qtde_estatistica', models.TextField(blank=True, db_column='QTDE ESTATISTICA', null=True)),
                ('peso_liquido', models.TextField(blank=True, db_column='PESO LIQUIDO', null=True)),
                ('vmle_dolar', models.TextField(blank=True, db_column='VMLE DOLAR', null=True)),
                ('vl_frete_dolar', models.TextField(blank=True, db_column='VL FRETE DOLAR', null=True)),
                ('vl_seguro_dolar', models.TextField(blank=True, db_column='VL SEGURO DOLAR', null=True)),
                ('valor_un_prod_dolar', models.TextField(blank=True, db_column='VALOR UN.PROD.DOLAR', null=True)),
                ('qtd_comercial_field', models.IntegerField(blank=True, db_column='QTD COMERCIAL.', null=True)),
                ('tot_un_prod_dolar', models.TextField(blank=True, db_column='TOT.UN.PROD.DOLAR', null=True)),
                ('unidade_desembarque', models.TextField(blank=True, db_column='UNIDADE DESEMBARQUE', null=True)),
                ('unidade_desembaraco', models.TextField(blank=True, db_column='UNIDADE DESEMBARACO', null=True)),
                ('incoterm', models.TextField(blank=True, db_column='INCOTERM', null=True)),
                ('nat_informacao', models.TextField(blank=True, db_column='NAT.INFORMACAO', null=True)),
                ('situacao_do_despacho', models.TextField(blank=True, db_column='SITUACAO DO DESPACHO', null=True)),
            ],
            options={
                'db_table': 'imp',
            },
        ),
    ]
